version: "3.9"

services:
  simulation:
    extends:
      file: ../auto_shepherd_simulation/docker/docker-compose.yml
      service: auto_shepherd_simulation_ros2_humble
    volumes:
      - ../auto_shepherd_simulation/auto_shepherd_simulation_ros2:/home/ros/base_ws/src/auto_simulation_ros2:rw
      - ../auto_shepherd_simulation/bash_scripts:/home/ros/bash_scripts:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ../auto_shepherd_simulation/configs/rviz:/home/ros/.rviz2:rw
      - ../auto_shepherd_simulation/configs/map:/home/ros/map:rw
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - BASE_WS=/home/ros/base_ws

  sheep_localisation:
    extends:
      file: ../auto_shepherd_sheep_localisation/docker/docker-compose.yml
      service: auto_shepherd_sheep_localisation_ros2
    volumes:
      - ../auto_shepherd_sheep_localisation/auto_shepherd_sheep_localisation_ros2:/home/ros/base_ws/src/auto_shepherd_sheep_localisation_ros2:rw
      - ../auto_shepherd_sheep_localisation/bash_scripts:/home/ros/bash_scripts:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - BASE_WS=/home/ros/base_ws
