services:

#  drone_control:
#    build:
#      context: ../auto_shepherd_drone_control
#      dockerfile: docker/Dockerfile
#    container_name: drone_control
#    hostname: drone_control
#    network_mode: bridge
#    ipc: "host"
#    tty: true
#    stdin_open: true
#    volumes:
#      - ../auto_shepherd_drone_control/auto_shepherd_drone_control_ros2:/home/ros/base_ws/src/auto_shepherd_drone_control_ros2:rw
#      - ../auto_shepherd_drone_control/bash_scripts/container:/home/ros/bash_scripts:rw
#      - /tmp/.X11-unix:/tmp/.X11-unix:rw
#    environment:
#      - DISPLAY=${DISPLAY}
#      - QT_X11_NO_MITSHM=1
#      - BASE_WS=/home/ros/base_ws
#      - ROS_DOMAIN_ID=0

  sheep_localisation:
    build:
      context: ../auto_shepherd_sheep_localisation
      dockerfile: docker/Dockerfile
    container_name: sheep_localisation
    hostname: sheep_localisation
    network_mode: bridge
    ipc: "host"
    tty: true
    stdin_open: true
    volumes:
      - ../auto_shepherd_sheep_localisation/auto_shepherd_sheep_localisation_ros2:/home/ros/base_ws/src/auto_shepherd_sheep_localisation_ros2:rw
      - ../auto_shepherd_sheep_localisation/bash_scripts/container:/home/ros/bash_scripts:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - BASE_WS=/home/ros/base_ws
      - ROS_DOMAIN_ID=0

  simulation:
    build:
      context: ../auto_shepherd_simulation
      dockerfile: docker/Dockerfile
    container_name: simulation
    hostname: simulation
    network_mode: bridge
    ipc: "host"
    tty: true
    stdin_open: true
    volumes:
      - ../auto_shepherd_simulation/auto_shepherd_simulation_ros2:/home/ros/base_ws/src/auto_shepherd_simulation_ros2:rw
      - ../auto_shepherd_simulation/bash_scripts/container:/home/ros/bash_scripts:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ../auto_shepherd_simulation/configs/rviz:/home/ros/.rviz2:rw
      - ../auto_shepherd_simulation/configs/map:/home/ros/map:rw
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - BASE_WS=/home/ros/base_ws
      - ROS_DOMAIN_ID=0

  communications_sim:
    build:
      context: ../auto_shepherd_communications
      dockerfile: docker/Dockerfile
    container_name: communications
    hostname: communications
    network_mode: bridge
    ipc: "host"
    tty: true
    stdin_open: true
    devices:
      - "/dev/ttyVserver:/dev/ttyVserver"
      - "/dev/ttyVrobot:/dev/ttyVrobot"
    group_add:
      - dialout
    volumes:
      - ../auto_shepherd_communications/auto_shepherd_communications_ros2:/home/ros/base_ws/src/auto_shepherd_communications_ros2:rw
      - ../auto_shepherd_communications/bash_scripts/container:/home/ros/bash_scripts:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - BASE_WS=/home/ros/base_ws
      - ROS_DOMAIN_ID=0
